# Generated by Django 4.1.5 on 2023-01-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now=True)),
                ('coffee_g', models.IntegerField()),
                ('water_brew_ml', models.IntegerField()),
                ('brew_time_s', models.TimeField()),
                ('milk_ml', models.IntegerField()),
                ('extra_water_ml', models.IntegerField(default=0)),
                ('nausea', models.BooleanField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6)),
            ],
        ),
    ]
