# Generated by Django 4.1.5 on 2023-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropress', '0002_alter_recipe_brew_time_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
