# Generated by Django 4.1.5 on 2023-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeropress', '0003_alter_recipe_datetime_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='to_del',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
