# Generated by Django 4.1.5 on 2023-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeropress', '0004_recipe_to_del'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='to_del',
        ),
    ]
